stages:
  - build
  - deploy

variables:
  IMAGE_NAME: votre-registry/votre-app
  TAG: latest

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client
    - ssh -o StrictHostKeyChecking=no user@votre-server "docker pull $IMAGE_NAME:$TAG && docker-compose up -d"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
